# Generated by Django 4.0.4 on 2022-06-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_job_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_notifications',
            new_name='Job_notification',
        ),
    ]
