# Generated by Django 4.0.4 on 2022-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_job_notification_ctc_job_notification_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_notification',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
