# Generated by Django 4.0.4 on 2022-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_job_notification_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_notification',
            name='img',
            field=models.ImageField(default='', max_length=500, upload_to=''),
        ),
    ]
