# Generated by Django 4.0.4 on 2022-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_alter_job_notification_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_prev_coding',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title1', models.CharField(max_length=100)),
                ('code1', models.CharField(max_length=2000, null=True)),
                ('title2', models.CharField(max_length=100)),
                ('code2', models.CharField(max_length=4000, null=True)),
            ],
        ),
    ]
