# Generated by Django 4.0.4 on 2022-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_company_prev_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_prev_coding',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
