# Generated by Django 4.0.4 on 2022-06-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0010_company_delete_company_prev_coding'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='solutions.company'),
        ),
    ]
