# Generated by Django 4.0.4 on 2022-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0011_solution_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
