# Generated by Django 4.0.4 on 2022-06-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0012_company_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20000),
        ),
    ]
