# Generated by Django 4.0.4 on 2022-06-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0013_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_notification',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
