# Generated by Django 4.0.4 on 2022-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0016_solution_description_solution_input_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='input_output',
            new_name='input_format',
        ),
        migrations.AddField(
            model_name='solution',
            name='output_format',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='solution',
            name='sample_input',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='solution',
            name='sample_output',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
