# Generated by Django 4.0.4 on 2022-06-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0017_rename_input_output_solution_input_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=4000)),
                ('is_script', models.BooleanField()),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='solutions.course')),
            ],
        ),
    ]
