# Generated by Django 4.0.4 on 2022-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0019_rename_company_quiz_course_quiz_choice1_quiz_choice2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='script',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
    ]
