# Generated by Django 4.0.4 on 2022-06-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0020_alter_quiz_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='script',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
